'use strict';

module.exports = [
  'function VERSION() view returns (uint16)',
  'function INSPECTION_PERIOD() view returns (uint16)',
  'function MAX_BLOCK_SIZE() view returns (uint16)',
  'function MAX_SOLUTION_SIZE() view returns (uint16)',
  'function BOND_AMOUNT() view returns (uint256)',
  'function createdAtBlock() view returns (uint256)',
  'function finalizedHeight() view returns (uint256)',
  'function canFinalizeBlock(uint256 blockNumber) view returns (bool)',
  'function getExit(address target, address owner) view returns (uint256)',
  'function getERC721Exit (address target, uint256 tokenId) view returns (address)',
  'function isERC721(address token, uint256 tokenId) view returns (bool)',
  'function deposit(address token, uint256 amountOrId)',
  'function withdraw(address token, uint256 tokenId)',
  'function submitBlock() payable',
  'function submitSolution(uint256 blockNumber, bytes32 solutionHash)',
  'function flagSolution(uint256 blockNumber, bytes32 solutionHash)',
  'function dispute()',
  'function finalizeSolution(uint256 blockNumber)',
  'event Deposit(address token, address owner, uint256 value)',
  'event BlockBeacon()',
  'event NewSolution(uint256 blockNumber, bytes32 solutionHash)',
];
