name: Continuous Integration

on:
  push:
    branches:
    - master
    - release/*

  pull_request:
    branches:
    - master

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Cache node modules
      uses: actions/cache@preview
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Setup
      run: |
        yarn
        sudo yarn global add codecov
        wget 'https://gethstore.blob.core.windows.net/builds/geth-linux-amd64-1.9.9-01744997.tar.gz' -O - | tar -xz
        sudo mkdir -p /usr/local/bin
        sudo mv geth-*/geth /usr/local/bin

    - name: Lint
      run: yarn lint

    - name: test:evm
      run: yarn test:evm

    - name: Coverage
      run: yarn coverage

    - name: Upload coverage to Codecov
      if: success()
      run: codecov -t ${{ secrets.CODECOV_TOKEN }} -B ${{ github.ref }} -f coverage-report.json
