name: Continuous Integration

on:
  push:
    branches:
    - master
    - release/*

  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Cache node modules
      uses: actions/cache@master
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Setup
      run: |
        yarn
        wget 'https://gethstore.blob.core.windows.net/builds/geth-linux-amd64-1.8.22-7fa3509e.tar.gz' -O - | tar -xz
        sudo mkdir -p /usr/local/bin
        sudo mv geth-*/geth /usr/local/bin

    - name: Lint
      run: yarn lint

    - name: Coverage
      run: yarn coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1.0.3
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: ./coverage-report.json
