name: Continuous Integration

on:
  push:
    branches:
    - master
    - release/*

  pull_request:
    branches:
    - master

jobs:
  build:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container: node:lts-alpine
    steps:
    - name: Setup
      run: |
        apk add --no-cache git geth
        yarn global add codecov

    - uses: actions/checkout@v2

    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install
      run: yarn install

    - name: Lint
      run: yarn lint

    - name: test:evm
      run: yarn test:evm

    - name: Coverage
      run: yarn coverage

    - name: Upload coverage to Codecov
      if: success()
      run: codecov -t ${{ secrets.CODECOV_TOKEN }} -B ${{ github.ref }} -f coverage-report.json
